### ISSUE TITLE
What is everybody going to be working on at the May 2022 Space Partitions Code Sprint - The 16th OGC API Code Sprint?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#12]
Post a comment letting us know what you are going to be working on.

**Comment by IvanSanchez** [comment]
I don't have a very specific plan, but I'll try to cover these:

- Read the Tiles spec in full
- Do a client implementation for [Gleo](https://gitlab.com/IvanSanchez/gleo)
- Consider a client implementation for [Leaflet](https://github.com/Leaflet/Leaflet/). _This might not be feasible_ due to how Leaflet hard-codes the levels of tile pyramids, even for proj4leaflet scenarios.
- Give commentary on how the Tiles spec fits (or doesn't fit?) vector tiles.

**Comment by b4l** [comment]
I will be working on https://github.com/camptocamp/ogcapi trying to improve EDR support, also may look at Tiles and investigate Coverages.

**Comment by pixportal** [comment]
I'm interested in getting to know EDR, Sam

**Comment by pixalytics** [comment]
I'm interested in getting to know EDR, Sam

**Comment by jerstlouis** [comment]
We will be completing and deploying our implementation of the draft [OGC API - DGGS](https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/tree/master/openapi), for an [axis-aligned DGGS](https://github.com/opengeospatial/dggs-4-axis-aligned/) based on the [GNOSIS Global Grid TileMatrixSet](https://docs.opengeospatial.org/DRAFTS/17-083r4.html#gnosis-global-grid-tilematrixset-definition).

Also planning to complete and deploy new [common building blocks](https://github.com/opengeospatial/ogcapi-coverages/issues/164) in our implementation of the Coverages and DGGS APIs for performing analytics across different APIs and data types (e.g., filtering and derived fields based on expressions), hopefully getting to implement support for analytics across multiple collections (both vector and raster).
